# Generated by Django 6.0.4 on 2026-04-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "time_slots",
                    models.JSONField(
                        default=list,
                        help_text='List of available time strings, e.g. ["10:00", "14:00"]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "availabilities",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="MockInterviewBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("slot_datetime", models.DateTimeField()),
                (
                    "focus_areas",
                    models.JSONField(
                        default=list,
                        help_text='e.g. ["system_design", "dsa", "ai_ml", "behavioral"]',
                    ),
                ),
                ("current_role", models.CharField(blank=True, max_length=200)),
                ("target_role", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=499.0, max_digits=8),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "phonepe_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "merchant_order_id",
                    models.CharField(blank=True, max_length=200, unique=True),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("meeting_link", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
