# Generated by Django 6.0.4 on 2026-04-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("tagline", models.CharField(max_length=300)),
                ("description", models.TextField(help_text="HTML content")),
                ("cover_image", models.URLField(blank=True)),
                ("gallery", models.JSONField(blank=True, default=list)),
                ("tech_tags", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AI_PRODUCT", "AI Product"),
                            ("SAAS", "SaaS"),
                            ("STARTUP", "Startup"),
                            ("CONSULTING", "Consulting"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"live": "https://...", "github": "https://...", "case_study": "https://..."}',
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=200)),
                ("role", models.CharField(blank=True, max_length=200)),
                (
                    "date_range",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Jan 2023 – Mar 2024"',
                        max_length=100,
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Lower number appears first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
